// <auto-generated />
using System;
using System.Collections.Generic;
using ArMenu.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArMenu.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ArMenuDbContext))]
    [Migration("20260916111516_AddMenuItemDietaryInformation")]
    partial class AddMenuItemDietaryInformation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArMenu.Domain.ArModels.ArModelProcessing", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("failure_code");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_item_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long>("SourceSize")
                        .HasColumnType("bigint")
                        .HasColumnName("source_size");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Report", "ArMenu.Domain.ArModels.ArModelProcessing.Report#ArModelReport", b1 =>
                        {
                            b1.PrimitiveCollection<string>("Warnings")
                                .IsRequired();

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Dimensions", "ArMenu.Domain.ArModels.ArModelProcessing.Report#ArModelReport.Dimensions#ModelDimensions", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<double>("Depth");

                                    b2.Property<double>("Height");

                                    b2.Property<double>("Width");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Files", "ArMenu.Domain.ArModels.ArModelProcessing.Report#ArModelReport.Files#ModelFileSizes", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<long>("AppleModel");

                                    b2.Property<long>("Model");

                                    b2.Property<long>("Poster");

                                    b2.Property<long>("SceneViewerModel");

                                    b2.Property<long>("Source");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Optimized", "ArMenu.Domain.ArModels.ArModelProcessing.Report#ArModelReport.Optimized#ModelStatistics", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Materials");

                                    b2.Property<int>("MaxTextureSize");

                                    b2.Property<int>("Textures");

                                    b2.Property<int>("Triangles");

                                    b2.Property<int>("Vertices");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Source", "ArMenu.Domain.ArModels.ArModelProcessing.Report#ArModelReport.Source#ModelStatistics", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Materials");

                                    b2.Property<int>("MaxTextureSize");

                                    b2.Property<int>("Textures");

                                    b2.Property<int>("Triangles");

                                    b2.Property<int>("Vertices");
                                });

                            b1
                                .ToJson("report")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("TenantId", "Id")
                        .HasName("pk_ar_model_processings");

                    b.HasIndex("TenantId", "MenuItemId", "CreatedAt")
                        .HasDatabaseName("ix_ar_model_processings_tenant_id_menu_item_id_created_at");

                    b.ToTable("ar_model_processings", (string)null);
                });

            modelBuilder.Entity("ArMenu.Domain.Memberships.TenantInvitation", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(43)
                        .HasColumnType("character(43)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId", "Id")
                        .HasName("pk_tenant_invitations");

                    b.HasIndex("InvitedBy")
                        .HasDatabaseName("ix_tenant_invitations_invited_by");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_invitations_tenant_id_email")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("tenant_invitations", (string)null);
                });

            modelBuilder.Entity("ArMenu.Domain.Memberships.TenantMembership", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TenantId", "Id")
                        .HasName("pk_tenant_memberships");

                    b.HasAlternateKey("TenantId", "UserId")
                        .HasName("ak_tenant_memberships_tenant_id_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tenant_memberships_user_id");

                    b.ToTable("tenant_memberships", (string)null);
                });

            modelBuilder.Entity("ArMenu.Domain.Menus.MenuCategory", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId", "Id")
                        .HasName("pk_menu_categories");

                    b.HasIndex("TenantId", "DisplayOrder")
                        .HasDatabaseName("ix_menu_categories_tenant_id_display_order")
                        .HasFilter("is_deleted = false");

                    b.ToTable("menu_categories", (string)null);
                });

            modelBuilder.Entity("ArMenu.Domain.Menus.MenuItem", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Allergens")
                        .HasColumnType("character varying(16)[]")
                        .HasColumnName("allergens");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.PrimitiveCollection<string[]>("DietaryLabels")
                        .IsRequired()
                        .HasColumnType("character varying(16)[]")
                        .HasColumnName("dietary_labels");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ArModel", "ArMenu.Domain.Menus.MenuItem.ArModel#ArModel", b1 =>
                        {
                            b1.Property<string>("GlbPath")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("ar_model_glb_path");

                            b1.Property<string>("PosterPath")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("ar_model_poster_path");

                            b1.Property<string>("SceneViewerGlbPath")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("ar_model_scene_viewer_glb_path");

                            b1.Property<string>("UsdzPath")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("ar_model_usdz_path");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "ArMenu.Domain.Menus.MenuItem.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("price_currency")
                                .IsFixedLength();
                        });

                    b.HasKey("TenantId", "Id")
                        .HasName("pk_menu_items");

                    b.HasIndex("TenantId", "CategoryId", "DisplayOrder")
                        .HasDatabaseName("ix_menu_items_tenant_id_category_id_display_order")
                        .HasFilter("is_deleted = false");

                    b.ToTable("menu_items", (string)null);
                });

            modelBuilder.Entity("ArMenu.Domain.Sessions.UserSession", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("PreviousRefreshTokenHash")
                        .HasMaxLength(43)
                        .HasColumnType("character(43)")
                        .HasColumnName("previous_refresh_token_hash")
                        .IsFixedLength();

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(43)
                        .HasColumnType("character(43)")
                        .HasColumnName("refresh_token_hash")
                        .IsFixedLength();

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TenantId", "Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("ix_user_sessions_tenant_id_user_id");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("ArMenu.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("DefaultCulture")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("default_culture");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PurgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purged_at");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string[]>("SupportedCultures")
                        .IsRequired()
                        .HasColumnType("character varying(12)[]")
                        .HasColumnName("supported_cultures");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Branding", "ArMenu.Domain.Tenants.Tenant.Branding#TenantBranding", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AccentColor")
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("branding_accent_color");

                            b1.Property<string>("LogoPath")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("branding_logo_path");
                        });

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("ArMenu.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<DateTimeOffset?>("ErasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("erased_at");

                    b.Property<int>("FailedSignInAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_sign_in_attempts");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("LastSignedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_signed_in_at");

                    b.Property<DateTimeOffset?>("LockedOutUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_out_until");

                    b.Property<DateTimeOffset?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ArMenu.Domain.Users.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(43)
                        .HasColumnType("character(43)")
                        .HasColumnName("hash")
                        .IsFixedLength();

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purpose");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_tokens");

                    b.HasIndex("UserId", "Purpose")
                        .HasDatabaseName("ix_user_tokens_user_id_purpose")
                        .HasFilter("consumed_at IS NULL");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("ArMenu.Infrastructure.ArModels.ArModelProcessingQueueEntry", b =>
                {
                    b.Property<Guid>("ProcessingId")
                        .HasColumnType("uuid")
                        .HasColumnName("processing_id");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("ProcessingId")
                        .HasName("pk_ar_model_processing_queue");

                    b.HasIndex("AvailableAt")
                        .HasDatabaseName("ix_ar_model_processing_queue_available_at");

                    b.HasIndex("TenantId", "ProcessingId")
                        .IsUnique()
                        .HasDatabaseName("ix_ar_model_processing_queue_tenant_id_processing_id");

                    b.ToTable("ar_model_processing_queue", (string)null);
                });

            modelBuilder.Entity("ArMenu.Infrastructure.Auditing.AuditLogEntry", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectName")
                        .HasColumnType("jsonb")
                        .HasColumnName("subject_name");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("subject_type");

                    b.HasKey("TenantId", "Id")
                        .HasName("pk_audit_log_entries");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_log_entries_actor_user_id");

                    b.ToTable("audit_log_entries", (string)null);
                });

            modelBuilder.Entity("ArMenu.Infrastructure.Mail.OutboxEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_body");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("language");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("template");

                    b.Property<string>("TextBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_body");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("to");

                    b.HasKey("Id")
                        .HasName("pk_email_outbox");

                    b.HasIndex("AvailableAt")
                        .HasDatabaseName("ix_email_outbox_available_at");

                    b.ToTable("email_outbox", (string)null);
                });

            modelBuilder.Entity("ArMenu.Infrastructure.Statistics.MenuDailyStatistic", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<string>("Event")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("event");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_item_id");

                    b.Property<long>("Count")
                        .HasColumnType("bigint")
                        .HasColumnName("count");

                    b.HasKey("TenantId", "Day", "Event", "MenuItemId")
                        .HasName("pk_menu_daily_statistics");

                    b.ToTable("menu_daily_statistics", (string)null);
                });

            modelBuilder.Entity("ArMenu.Domain.ArModels.ArModelProcessing", b =>
                {
                    b.HasOne("ArMenu.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ar_model_processings_tenants_tenant_id");

                    b.HasOne("ArMenu.Domain.Menus.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ar_model_processings_menu_items_tenant_id_menu_item_id");
                });

            modelBuilder.Entity("ArMenu.Domain.Memberships.TenantInvitation", b =>
                {
                    b.HasOne("ArMenu.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_invitations_users_invited_by");

                    b.HasOne("ArMenu.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_invitations_tenants_tenant_id");
                });

            modelBuilder.Entity("ArMenu.Domain.Memberships.TenantMembership", b =>
                {
                    b.HasOne("ArMenu.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_memberships_tenants_tenant_id");

                    b.HasOne("ArMenu.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_memberships_users_user_id");
                });

            modelBuilder.Entity("ArMenu.Domain.Menus.MenuCategory", b =>
                {
                    b.HasOne("ArMenu.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_menu_categories_tenants_tenant_id");
                });

            modelBuilder.Entity("ArMenu.Domain.Menus.MenuItem", b =>
                {
                    b.HasOne("ArMenu.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_menu_items_tenants_tenant_id");

                    b.HasOne("ArMenu.Domain.Menus.MenuCategory", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_menu_items_menu_categories_tenant_id_category_id");
                });

            modelBuilder.Entity("ArMenu.Domain.Sessions.UserSession", b =>
                {
                    b.HasOne("ArMenu.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_tenants_tenant_id");

                    b.HasOne("ArMenu.Domain.Memberships.TenantMembership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "UserId")
                        .HasPrincipalKey("TenantId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_tenant_memberships_tenant_id_user_id");
                });

            modelBuilder.Entity("ArMenu.Domain.Users.UserToken", b =>
                {
                    b.HasOne("ArMenu.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("ArMenu.Infrastructure.ArModels.ArModelProcessingQueueEntry", b =>
                {
                    b.HasOne("ArMenu.Domain.ArModels.ArModelProcessing", null)
                        .WithOne()
                        .HasForeignKey("ArMenu.Infrastructure.ArModels.ArModelProcessingQueueEntry", "TenantId", "ProcessingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ar_model_processing_queue_ar_model_processings_tenant_id_pr");
                });

            modelBuilder.Entity("ArMenu.Infrastructure.Auditing.AuditLogEntry", b =>
                {
                    b.HasOne("ArMenu.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_log_entries_users_actor_user_id");

                    b.HasOne("ArMenu.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_entries_tenants_tenant_id");
                });

            modelBuilder.Entity("ArMenu.Infrastructure.Statistics.MenuDailyStatistic", b =>
                {
                    b.HasOne("ArMenu.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_menu_daily_statistics_tenants_tenant_id");
                });
#pragma warning restore 612, 618
        }
    }
}
